### ISSUE TITLE
Add a Picture State to the FrontEnd

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning/wearable-learning-cloud-platform#14]
a.	Current DisplayText state will be used as an example
b.	JavaScript Controller : https://github.com/wearable-learning/wearable-learning-cloud-platform/blob/master/WLCPFrontEnd/WebContent/wlcpfrontend/javascript/GameEditor/state/StateConfig/StateConfigDisplayText.js 
c.	XML Fragment : https://github.com/wearable-learning/wearable-learning-cloud-platform/blob/master/WLCPFrontEnd/WebContent/wlcpfrontend/fragments/GameEditor/States/OutputStateDisplayTextConfig.fragment.xml 
d.	SAP OPENUI5 Documentation can be found here : https://openui5.hana.ondemand.com/ specifically looks at API reference and Samples for how to work with XML controls and javascript controllers

**Comment by rcvalenteai** [comment]
e. Add object to  Line 55 -wearable-learning-cloud-platform/WLCPFrontEnd/WebContent/wlcpfrontend/javascript/GameEditor/state/OutputState.js
f. Add javascript to index.js
wearable-learning-cloud-platform/WLCPFrontEnd/WebContent/index.js
